FROM confluentinc/cp-spark:7.0.0

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["spark-submit", "--master", "local[*]", "src/processing/spark_batch.py"]
